DROP TABLE TICKET;
DROP TABLE debt;
DROP TABLE USER_TICKET;
CREATE TABLE TICKET(
  PL_ID  NUMBER GENERATED ALWAYS AS IDENTITY,
  PL_NAME VARCHAR2(30),
  DEP_DATE DATE,
  PRICE NUMBER,
  PASS_NUM NUMBER,
  CONSTRAINT PK_TICKET PRIMARY KEY (PL_ID)
);
CREATE TABLE USER_TICKET(
  USER_ID NUMBER GENERATED ALWAYS AS IDENTITY,
  NAME  VARCHAR2(30),
  SURNAME VARCHAR2(30),
  MONEY NUMBER,
 -- pass varchar2(500),
  CONSTRAINT PK_USER_TICKET PRIMARY KEY (USER_ID)
);


SELECT * FROM 


UPDATE TICKET
SET PRICE = ROUND(DBMS_RANDOM.VALUE(7, 15), 1)
WHERE 1=1;


SELECT * FROM TICKET;
SELECT * FROM USER_TICKET;