

SELECT * FROM TICKET;
SELECT * FROM USER_TICKET;


SET serveroutput ON;
EXECUTE upd_place(6,3,15);

CREATE OR REPLACE PROCEDURE upd_place(user_id_yz IN NUMBER, PL_ID_YZ IN NUMBER, PASS_NUM_Y IN NUMBER) IS  --PASS_NUM_Y BILET SAYI,,PL_ID_YZ MEKANIN Adi,,user_id istifadeci adi 
  v_USER_ID USER_TICKET.USER_ID%type;
  v_PL_ID TICKET.PL_ID%type;
  v_PRICE TICKET.PRICE%type;
  v_BALANCE USER_TICKET.MONEY%type;
  V_PASS_NUM TICKET.PASS_NUM%type;
  V_PASS_SO NUMBER;
  FERQ NUMBER;
  V_DEP_DATE TICKET.DEP_DATE%TYPE;
  V_UPDATED_DEP_DATE TICKET.DEP_DATE%TYPE; 
BEGIN
  SELECT USER_ID, MONEY INTO v_USER_ID, v_BALANCE FROM USER_TICKET WHERE USER_ID = user_id_yz;
  SELECT PL_ID, PRICE, PASS_NUM, DEP_DATE INTO v_PL_ID, v_PRICE, V_PASS_NUM, V_DEP_DATE FROM TICKET WHERE PL_ID = PL_ID_YZ;

  FERQ := v_BALANCE - (PASS_NUM_Y * v_PRICE);
  V_PASS_SO := V_PASS_NUM - PASS_NUM_Y;
  V_UPDATED_DEP_DATE := V_DEP_DATE + 1;

  IF V_PASS_NUM > 0 THEN
    IF v_BALANCE >= PASS_NUM_Y * v_PRICE THEN
      UPDATE TICKET SET PASS_NUM = V_PASS_SO WHERE PL_ID = PL_ID_YZ;
      UPDATE USER_TICKET SET MONEY = FERQ WHERE USER_ID = user_id_yz;
    ELSE
      dbms_output.put_line('Yeterli m?bl?? yoxdur');
    END IF;
  ELSIF V_PASS_NUM = 0 THEN
    UPDATE TICKET SET DEP_DATE = V_UPDATED_DEP_DATE WHERE PL_ID = PL_ID_YZ;
    dbms_output.put_line('TEST');
   -- UPDATE TICKET SET PASS_NUM = 20 WHERE PL_ID = PL_ID_YZ;
  ELSE
    dbms_output.put_line('Bilet mövcud deyil');
  END IF;
EXCEPTION
  WHEN NO_DATA_FOUND THEN
    DBMS_OUTPUT.PUT_LINE('M?lumat tap?lmad?.');
  WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('S?hv ba? verdi: ' || SQLERRM);
END;
