SELECT EMPNO,ENAME,SAL,RANK() OVER (ORDER BY SAL ASC) AS salary_rank FROM EMP;


SELECT EMPNO,ENAME,SAL,RANK() OVER (ORDER BY SAL DESC) AS salary_rank FROM EMP;


--RANK() OVER SIRALAMANI RUTBELEYIR\\\\\\\\\\\\\\\\\BURADA EYNI DEYER OLANDA  ONU FERQLI SIRALAMA ILE DAVAM  EDIR MESELEN 2 SI EYNIDI 1-1 SONRA 2 YAZMAQ YERINE 3 YAZIR 
-----------------------------------------------------------------------------------------
--DENSE_RANK()
SELECT EMPNO,ENAME,SAL,DENSE_RANK() OVER (ORDER BY SAL ASC) AS salary_rank FROM EMP; --BURADA ISE 1-1SONRA 2
---------------------------------------------------------------------------------------------
--ROW_NUMBER()  EYNI OLANA BAXMIR DAVAM EDIR

SELECT EMPNO,ENAME,SAL,ROW_NUMBER() OVER (ORDER BY SAL DESC) AS salary_rank FROM EMP;
---------------------------------------------------------------
--SAYCA QRUPLARA BOLUR
SELECT EMPNO,ENAME,SAL,NTILE(4) OVER (ORDER BY SAL DESC) AS salary_rank FROM EMP;

---------------------------------------------------------------------

SELECT * FROM ORDERS;
SELECT * FROM CUSTOMERS;

SELECT NAME,ADDRESS,WEBSITE,CREDIT_LIMIT FROM CUSTOMERS WHERE CUSTOMER_ID IN (SELECT CUSTOMER_ID FROM ORDERS WHERE STATUS = 'PENDING');
SELECT NAME,ADDRESS,WEBSITE,CREDIT_LIMIT FROM CUSTOMERS WHERE CUSTOMER_ID IN (SELECT CUSTOMER_ID FROM ORDERS WHERE STATUS = 'CANCELED');
SELECT NAME,ADDRESS,WEBSITE,CREDIT_LIMIT FROM CUSTOMERS WHERE CUSTOMER_ID IN (SELECT CUSTOMER_ID FROM ORDERS WHERE STATUS = 'SHIPPED');
----------------------------------------------------------------------------------------------

--
SELECT B.BOOK_ID,b.PRICE*S.SALES_AMOUNT TOTAL FROM books b
inner join salE s using(BOOK_ID) ;

SELECT B.BOOK_ID,B.BOOK_NAME, B.PRICE * S.SALES_AMOUNT AS TOTAL
FROM BOOKS B
INNER JOIN SALE S ON B.BOOK_ID =S.BOOK_ID;

----------------------------------------------------------------
/*SYSDATE, CURRENT_DATE, SYSTIMESTAMP,EXTRACT, TO_DATE , TO_CHAR, ADD_MONTHS, MONTHS_BETWEEN, LAST_DAY, TRUNC, ROUND,NEXT_DAY)*/